### ISSUE TITLE
Installing error

### ISSUE THREAD

**Issue by ui1223** [ashawkey/diff-gaussian-rasterization#8]
Hi I got a problem while I was installing
the error is shown below
(DreamG) E:\2.code\dreamgaussian>pip install ./diff-gaussian-rasterization
Processing e:\2.code\dreamgaussian\diff-gaussian-rasterization
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: diff-gaussian-rasterization
  Building wheel for diff-gaussian-rasterization (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [62 lines of output]
      No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3'
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\diff_gaussian_rasterization
      copying diff_gaussian_rasterization\__init__.py -> build\lib.win-amd64-cpython-311\diff_gaussian_rasterization
      running build_ext
      C:\Users\l1188\anaconda3\envs\DreamG\Lib\site-packages\torch\utils\cpp_extension.py:383: UserWarning: Error checking compiler version for cl: [WinError 2] system can not find the file
        warnings.warn(f'Error checking compiler version for {compiler}: {error}')
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "E:\2.code\dreamgaussian\diff-gaussian-rasterization\setup.py", line 17, in <module>
          setup(
        File "C:\Users\l1188\anaconda3\envs\DreamG\Lib\site-packages\setuptools\__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\l1188\anaconda3\envs\DreamG\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\l1188\anaconda3\envs\DreamG\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\l1188\anaconda3\envs\DreamG\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\l1188\anaconda3\envs\DreamG\Lib\site-packages\setuptools\dist.py", line 1234, in run_command
          super().run_command(command)
        File "C:\Users\l1188\anaconda3\envs\DreamG\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\l1188\anaconda3\envs\DreamG\Lib\site-packages\wheel\bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "C:\Users\l1188\anaconda3\envs\DreamG\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\l1188\anaconda3\envs\DreamG\Lib\site-packages\setuptools\dist.py", line 1234, in run_command
          super().run_command(command)
        File "C:\Users\l1188\anaconda3\envs\DreamG\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\l1188\anaconda3\envs\DreamG\Lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\Users\l1188\anaconda3\envs\DreamG\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\l1188\anaconda3\envs\DreamG\Lib\site-packages\setuptools\dist.py", line 1234, in run_command
          super().run_command(command)
        File "C:\Users\l1188\anaconda3\envs\DreamG\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\l1188\anaconda3\envs\DreamG\Lib\site-packages\setuptools\command\build_ext.py", line 84, in run
          _build_ext.run(self)
        File "C:\Users\l1188\anaconda3\envs\DreamG\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
          self.build_extensions()
        File "C:\Users\l1188\anaconda3\envs\DreamG\Lib\site-packages\torch\utils\cpp_extension.py", line 525, in build_extensions
          _check_cuda_version(compiler_name, compiler_version)
        File "C:\Users\l1188\anaconda3\envs\DreamG\Lib\site-packages\torch\utils\cpp_extension.py", line 407, in _check_cuda_version
          torch_cuda_version = packaging.version.parse(torch.version.cuda)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\l1188\anaconda3\envs\DreamG\Lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 52, in parse
          return Version(version)
                 ^^^^^^^^^^^^^^^^
        File "C:\Users\l1188\anaconda3\envs\DreamG\Lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 196, in __init__
          match = self._regex.search(version)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      TypeError: expected string or bytes-like object, got 'NoneType'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for diff-gaussian-rasterization
  Running setup.py clean for diff-gaussian-rasterization
Failed to build diff-gaussian-rasterization
ERROR: Could not build wheels for diff-gaussian-rasterization, which is required to install pyproject.toml-based projects

could you help me with that?

**Comment by 520jz** [comment]
Hello, I have the same problem as you, did you solve this problem？

**Comment by 520jz** [comment]
> Hi I got a problem while I was installing the error is shown below (DreamG) E:\2.code\dreamgaussian>pip install ./diff-gaussian-rasterization Processing e:\2.code\dreamgaussian\diff-gaussian-rasterization Preparing metadata (setup.py) ... done Building wheels for collected packages: diff-gaussian-rasterization Building wheel for diff-gaussian-rasterization (setup.py) ... error error: subprocess-exited-with-error
> 
> × python setup.py bdist_wheel did not run successfully. │ exit code: 1 ╰─> [62 lines of output] No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3' running bdist_wheel running build running build_py creating build creating build\lib.win-amd64-cpython-311 creating build\lib.win-amd64-cpython-311\diff_gaussian_rasterization copying diff_gaussian_rasterization__init__.py -> build\lib.win-amd64-cpython-311\diff_gaussian_rasterization running build_ext C:\Users\l1188\anaconda3\envs\DreamG\Lib\site-packages\torch\utils\cpp_extension.py:383: UserWarning: Error checking compiler version for cl: [WinError 2] system can not find the file warnings.warn(f'Error checking compiler version for {compiler}: {error}') Traceback (most recent call last): File "", line 2, in File "", line 34, in File "E:\2.code\dreamgaussian\diff-gaussian-rasterization\setup.py", line 17, in setup( File "C:\Users\l1188\anaconda3\envs\DreamG\Lib\site-packages\setuptools__init__.py", line 107, in setup return distutils.core.setup(**attrs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\l1188\anaconda3\envs\DreamG\Lib\site-packages\setuptools_distutils\core.py", line 185, in setup return run_commands(dist) ^^^^^^^^^^^^^^^^^^ File "C:\Users\l1188\anaconda3\envs\DreamG\Lib\site-packages\setuptools_distutils\core.py", line 201, in run_commands dist.run_commands() File "C:\Users\l1188\anaconda3\envs\DreamG\Lib\site-packages\setuptools_distutils\dist.py", line 969, in run_commands self.run_command(cmd) File "C:\Users\l1188\anaconda3\envs\DreamG\Lib\site-packages\setuptools\dist.py", line 1234, in run_command super().run_command(command) File "C:\Users\l1188\anaconda3\envs\DreamG\Lib\site-packages\setuptools_distutils\dist.py", line 988, in run_command cmd_obj.run() File "C:\Users\l1188\anaconda3\envs\DreamG\Lib\site-packages\wheel\bdist_wheel.py", line 364, in run self.run_command("build") File "C:\Users\l1188\anaconda3\envs\DreamG\Lib\site-packages\setuptools_distutils\cmd.py", line 318, in run_command self.distribution.run_command(command) File "C:\Users\l1188\anaconda3\envs\DreamG\Lib\site-packages\setuptools\dist.py", line 1234, in run_command super().run_command(command) File "C:\Users\l1188\anaconda3\envs\DreamG\Lib\site-packages\setuptools_distutils\dist.py", line 988, in run_command cmd_obj.run() File "C:\Users\l1188\anaconda3\envs\DreamG\Lib\site-packages\setuptools_distutils\command\build.py", line 131, in run self.run_command(cmd_name) File "C:\Users\l1188\anaconda3\envs\DreamG\Lib\site-packages\setuptools_distutils\cmd.py", line 318, in run_command self.distribution.run_command(command) File "C:\Users\l1188\anaconda3\envs\DreamG\Lib\site-packages\setuptools\dist.py", line 1234, in run_command super().run_command(command) File "C:\Users\l1188\anaconda3\envs\DreamG\Lib\site-packages\setuptools_distutils\dist.py", line 988, in run_command cmd_obj.run() File "C:\Users\l1188\anaconda3\envs\DreamG\Lib\site-packages\setuptools\command\build_ext.py", line 84, in run _build_ext.run(self) File "C:\Users\l1188\anaconda3\envs\DreamG\Lib\site-packages\setuptools_distutils\command\build_ext.py", line 345, in run self.build_extensions() File "C:\Users\l1188\anaconda3\envs\DreamG\Lib\site-packages\torch\utils\cpp_extension.py", line 525, in build_extensions _check_cuda_version(compiler_name, compiler_version) File "C:\Users\l1188\anaconda3\envs\DreamG\Lib\site-packages\torch\utils\cpp_extension.py", line 407, in _check_cuda_version torch_cuda_version = packaging.version.parse(torch.version.cuda) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\l1188\anaconda3\envs\DreamG\Lib\site-packages\pkg_resources_vendor\packaging\version.py", line 52, in parse return Version(version) ^^^^^^^^^^^^^^^^ File "C:\Users\l1188\anaconda3\envs\DreamG\Lib\site-packages\pkg_resources_vendor\packaging\version.py", line 196, in **init** match = self._regex.search(version) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ TypeError: expected string or bytes-like object, got 'NoneType' [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for diff-gaussian-rasterization Running setup.py clean for diff-gaussian-rasterization Failed to build diff-gaussian-rasterization ERROR: Could not build wheels for diff-gaussian-rasterization, which is required to install pyproject.toml-based projects
> 
> could you help me with that?

Hello, I have the same problem as you, did you solve this problem

**Comment by deandimarzo** [comment]
experiencing the same exact problem here.

**Comment by howitzer99** [comment]
I'm also experiencing an issue with installation.

I've tried setting my CUDA_HOME to versions 11.7, 12.1, and the latest 12.3 but I always get TraceBack errors when running the `git install` command.

I've also generated and installed a requirements file, again, no luck.

Can someone please help with this?

**Comment by CGMikeG** [comment]
Hello all, 

I tried installing below version of pytorch and it work for me.

conda install pytorch==2.1.0 torchvision==0.16.0 torchaudio==2.1.0 pytorch-cuda=11.8 -c pytorch -c nvidia
https://pytorch.org/get-started/previous-versions/

Make sure you use the correct version that matches your cuda version

**Comment by salier** [comment]
PS D:\dreamgaussian_qinglong> pip show torch
Name: torch
Version: 2.1.0
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: c:\users\dell\appdata\local\programs\python\python310\lib\site-packages
Requires: filelock, fsspec, jinja2, networkx, sympy, typing-extensions
Required-by: torchaudio, torchvision

**Comment by TGYY** [comment]
> Hello, I am using your configuration but still reporting an error. I would like to know which version is usable. PS D:\dreamgaussian_qinglong> pip install torch==2.1.0 torchvision==0.16.0 torchaudio==2.1.0 Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple Collecting torch==2.1.0 Downloading https://pypi.tuna.tsinghua.edu.cn/packages/fa/47/1a7daf04f40715fc1cdc6f1cc3200228a556d06c843e6ceb58883b745e1b/torch-2.1.0-cp310-cp310-win_amd64.whl (192.3 MB) ---------------------------------------- 192.3/192.3 MB 9.6 MB/s eta 0:00:00 Collecting torchvision==0.16.0 Downloading https://pypi.tuna.tsinghua.edu.cn/packages/59/af/426c2b90f5c4f8aba778746465af9e662680570e950e02379e91c6138285/torchvision-0.16.0-cp310-cp310-win_amd64.whl (1.3 MB) ---------------------------------------- 1.3/1.3 MB 11.5 MB/s eta 0:00:00 Collecting torchaudio==2.1.0 Downloading https://pypi.tuna.tsinghua.edu.cn/packages/6b/ba/0e26883fd90f280452bed7edc7906ef9253255f395702751f65fa02afb5c/torchaudio-2.1.0-cp310-cp310-win_amd64.whl (2.3 MB) ---------------------------------------- 2.3/2.3 MB 11.4 MB/s eta 0:00:00 Requirement already satisfied: filelock in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from torch==2.1.0) (3.13.1) Requirement already satisfied: typing-extensions in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from torch==2.1.0) (4.9.0) Requirement already satisfied: sympy in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from torch==2.1.0) (1.12) Requirement already satisfied: networkx in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from torch==2.1.0) (3.2.1) Requirement already satisfied: jinja2 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from torch==2.1.0) (3.1.3) Requirement already satisfied: fsspec in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from torch==2.1.0) (2023.12.2) Requirement already satisfied: numpy in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from torchvision==0.16.0) (1.26.3) Requirement already satisfied: requests in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from torchvision==0.16.0) (2.30.0) Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from torchvision==0.16.0) (9.3.0) Requirement already satisfied: MarkupSafe>=2.0 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from jinja2->torch==2.1.0) (2.1.3) Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from requests->torchvision==0.16.0) (3.1.0) Requirement already satisfied: idna<4,>=2.5 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from requests->torchvision==0.16.0) (3.4) Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from requests->torchvision==0.16.0) (2.0.2) Requirement already satisfied: certifi>=2017.4.17 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from requests->torchvision==0.16.0) (2023.5.7) Requirement already satisfied: mpmath>=0.19 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from sympy->torch==2.1.0) (1.3.0) Installing collected packages: torch, torchvision, torchaudio Successfully installed torch-2.1.0 torchaudio-2.1.0 torchvision-0.16.0 PS D:\dreamgaussian_qinglong> pip install ./diff-gaussian-rasterization Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple Processing d:\dreamgaussian_qinglong\diff-gaussian-rasterization Installing build dependencies ... done Getting requirements to build wheel ... error error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> [17 lines of output] Traceback (most recent call last): File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\pip_vendor\pyproject_hooks_in_process_in_process.py", line 353, in main() File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\pip_vendor\pyproject_hooks_in_process_in_process.py", line 335, in main json_out['return_val'] = hook(**hook_input['kwargs']) File "C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\pip_vendor\pyproject_hooks_in_process_in_process.py", line 118, in get_requires_for_build_wheel return hook(config_settings) File "C:\Users\DELL\AppData\Local\Temp\pip-build-env-vtfai84a\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel return self._get_build_requires(config_settings, requirements=['wheel']) File "C:\Users\DELL\AppData\Local\Temp\pip-build-env-vtfai84a\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires self.run_setup() File "C:\Users\DELL\AppData\Local\Temp\pip-build-env-vtfai84a\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script) File "C:\Users\DELL\AppData\Local\Temp\pip-build-env-vtfai84a\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup exec(code, locals()) File "", line 13, in ModuleNotFoundError: No module named 'torch' [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.

I met the same problem as you, I use "python setup.py install" but not pip to install, and it works. Hope it helps you.

**Comment by xusongxuliangwangsulong** [comment]
https://github.com/ashawkey/diff-gaussian-rasterization/issues/10

**Comment by StevenHong** [comment]
Hello, I'm having the same issue with this line.
```
match = self._regex.search(version)
TypeError: expected string or bytes-like object
```
The way I fixed it is using the following combo
- python=3.10
- cudatoolkit=11.6
- pip=22.3.1
- pytorch=1.12.1
- torchaudio=0.12.1
- torchvision=0.13.1

I think the key is python3.10 version. I tried python3.7.13 and python3.9 but it gave me error.

My machine: Linux Ubuntu 22.04 with cuda 11.8 installed in /usr/local/cuda-11.8
